[package]
name = "cmprss"
version = "0.1.0"
edition = "2021"
authors = ["Patrick Jackson <patrick@jackson.dev>"]
readme = "README.md"
license = "MIT"
description = "A compression multi-tool for the command line."
repository = "https://github.com/arcuru/cmprss"
homepage = "https://github.com/arcuru/cmprss"
categories = ["command-line-utilities", "compression"]

[dependencies]
bzip2 = "0.4.4"
clap = { version = "4.2.1", features = ["derive"] }
flate2 = "1.0"
indicatif = "0.17.7"
is-terminal = "0.4"
tar = "0.4.38"
xz2 = "0.1.7"

[dev-dependencies]
assert_cmd = "2.0.11"
assert_fs = "1.0.12"
predicates = "3.0.2"
