[package]
name = "cmprss"
version = "0.2.0"
edition = "2021"
authors = ["Patrick Jackson <patrick@jackson.dev>"]
readme = "README.md"
license = "MIT"
description = "A compression multi-tool for the command line."
repository = "https://github.com/arcuru/cmprss"
homepage = "https://github.com/arcuru/cmprss"
categories = ["command-line-utilities", "compression"]

[dependencies]
bzip2 = { version = "0.5", features = ["static"] }
clap = { version = "4", features = ["derive"] }
flate2 = "1"
indicatif = "0.17"
is-terminal = "0.4"
tar = "0.4"
xz2 = "0.1"
zip = "0.6"
tempfile = "3"
zstd = "0.13"
lz4_flex = "0.11"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "3"
rand = "0.8"

[features]
default = ["interop"]
interop = []
