[package]
name = "cmprss"
version = "0.0.1"
edition = "2021"
authors = ["Patrick Jackson <patrick@jackson.dev>"]
readme = "README.md"
license = "MIT"
description = "cmprss - a compression multi-tool for the CLI"
repository = "https://github.com/patricksjackson/cmprss"
homepage = "https://github.com/patricksjackson/cmprss"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
flate2 = "1.0"
tar = "0.4.38"
is-terminal = "0.4"

