[advisories]

[bans]
multiple-versions = "warn"

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "bzip2-1.0.6",
    "CC0-1.0",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
confidence-threshold = 0.95
