name: Codeberg Sync

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  mirror:
    uses: arcuru/actions/.github/workflows/codeberg-mirror.yml@c8144123ad5a2c6316b7becab8233b68dfa637d9 # v0.2.1
    with:
      destination: git@codeberg.org:arcuru/cmprss.git
    secrets:
      ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
